### ISSUE TITLE
RN 0.72.3 + fabric enabled => RNCProgressViewComponentDescriptors.h file not found ?

### ISSUE THREAD

**Issue by zabojad** [react-native-progress-view/progress-view#131]
I just freshly installed `@react-native-community/progress-view` on my RN 0.72.3 project with fabric enabled.

Trying to build the project in XCode now fails with error: `node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:6:9 'react/renderer/components/progressview/RNCProgressViewComponentDescriptors.h' file not found`

<img width="1574" alt="Screenshot 2023-07-18 at 16 56 00" src="https://github.com/react-native-progress-view/progress-view/assets/1238030/f17fb49c-c62f-4cb5-86b6-02d7d6f195b6">

Anyone getting this too?

**Comment by zabojad** [comment]
If I debug what codegen does with this:

```sh
node node_modules/react-native/scripts/generate-codegen-artifacts.js --path ./ --outputPath ./ios-debug
```

I indeed get slightly different filenames that what is imported in `RNCProgressViewComponentView.mm`:

<img width="250" alt="Screenshot 2023-07-18 at 17 01 46" src="https://github.com/react-native-progress-view/progress-view/assets/1238030/e04e77e7-f18e-49ef-ab69-8352412d75e2">

**Comment by zabojad** [comment]
Now if I "fix" those imports with the right pathes given by codegen debug, I get other errors:

```
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:114:28: error: unknown type name 'ImageRequest'
  auto getCoordinator = [](ImageRequest const *request) -> ImageResponseObserverCoordinator const * {
                           ^
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:122:33: error: no member named 'getProgressImageSource' in 'facebook::react::RNCProgressViewState'
  if (!havePreviousData || data.getProgressImageSource() != _oldState->getData().getProgressImageSource()) {
                           ~~~~ ^
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:122:82: error: no member named 'getProgressImageSource' in 'facebook::react::RNCProgressViewState'
  if (!havePreviousData || data.getProgressImageSource() != _oldState->getData().getProgressImageSource()) {
                                                            ~~~~~~~~~~~~~~~~~~~~ ^
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:123:58: error: no member named 'getProgressImageRequest' in 'facebook::react::RNCProgressViewState'
    self.progressImageCoordinator = getCoordinator(&data.getProgressImageRequest());
                                                    ~~~~ ^
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:126:33: error: no member named 'getTrackImageSource' in 'facebook::react::RNCProgressViewState'
  if (!havePreviousData || data.getTrackImageSource() != _oldState->getData().getTrackImageSource()) {
                           ~~~~ ^
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:126:79: error: no member named 'getTrackImageSource' in 'facebook::react::RNCProgressViewState'
  if (!havePreviousData || data.getTrackImageSource() != _oldState->getData().getTrackImageSource()) {
                                                         ~~~~~~~~~~~~~~~~~~~~ ^
/Users/thomasfetiveau/wksp_myproj/my-proj/node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:127:55: error: no member named 'getTrackImageRequest' in 'facebook::react::RNCProgressViewState'
    self.trackImageCoordinator = getCoordinator(&data.getTrackImageRequest());
```

😭😭😭

**Comment by stee1ix** [comment]
I'm facing this issue as well.

**Comment by nutstick** [comment]
Hi @zabojad, I have try to reproduce the issue using fresh created project but it's work fine on my end. Regarding the comment

> Trying to build the project in XCode now fails with error: node_modules/@react-native-community/progress-view/ios/Fabric/RNCProgressViewComponentView.mm:6:9 'react/renderer/components/progressview/RNCProgressViewComponentDescriptors.h' file not found

The import path should be expected as it intented to point to generate file directly, but it import from [here](https://github.com/react-native-progress-view/progress-view/blob/master/common/cpp/react/renderer/components/progressview/RNCProgressViewComponentDescriptors.h). I think might need to check if `common/cpp` is included as source files when you build.

**Comment by nutstick** [comment]
I just found that publish package is missing the common folder (which is where RNCProgressViewComponentView .mm located). I have created https://github.com/react-native-progress-view/progress-view/pull/136 for the fix.
