### ISSUE TITLE
Module not found: Can't resolve './ProgressView'

### ISSUE THREAD

**Issue by vipulswarup** [react-native-progress-view/progress-view#43]
Hi I am trying to use this component in an Expo (3.25.0) project.
I have installed using npm install 
```
npm install @react-native-community/progress-view --save
```

I am getting the below error when running ... any help appreciated
```
Module not found: Can't resolve './ProgressView'
```

**Comment by Rainshard** [comment]
Did you solve this?

**Comment by vipulswarup** [comment]
Couldn't use Expo. Had to use a react native CLI project instead. It worked in that.

**Comment by Naturalclar** [comment]
Unfortunately, this module will not work with expo in managed workflow, as expo only supports pre-installed native modules
