### ISSUE TITLE
Xcode 12 compatibility

### ISSUE THREAD

**Issue by Pranit-Harekar** [react-native-progress-view/progress-view#61]
Builds on Xcode 12 and above fail due to this library. 

![image](https://user-images.githubusercontent.com/17886017/117314004-616dbe00-ae54-11eb-95eb-be7a5b51144e.png)

The issues seems to be related to [this](https://github.com/facebook/react-native/issues/29633). To fix it we would need to make changes as mentioned [here](https://github.com/facebook/react-native/issues/29633#issuecomment-826620412) to the podspec,

```diff
- s.dependency     'React'
+ s.dependency     'React-Core'
```

https://github.com/wonday/react-native-pdf/pull/509/files#diff-5faac750e13626b2dc95e4621e009a7130bc2919068cd64ae68beb55e0899344L17-R17

**Comment by Naturalclar** [comment]
@Pranit-Harekar published v1.3.1 with your fix, thanks!
