### ISSUE TITLE
Support new React Native new architecture (TurboModules/Fabric)

### ISSUE THREAD

**Issue by tom-sherman** [react-native-progress-view/progress-view#91]
See https://reactnative.dev/docs/new-architecture-library-intro

https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture

**Comment by nutstick** [comment]
Hi, If no one's working on it yet, I can try to work on it.

**Comment by ShivamJoker** [comment]
Will be great to have this done
